### ISSUE TITLE
Unlock Failed

### ISSUE THREAD

**Issue by shadeimi** [askervin/fmbt-androidtest#5]
10:10 $ fmbt regressiontest.conf 
<fmbt_log>
<version>
    0.31-0.rc0-46a6276
</version>
<conf_load>
    <conf_file name="regressiontest.conf"/>
     <remote_pyaal_version>0.31-0.rc0-46a6276</remote_pyaal_version>
</conf_load>
<conf_execute>
    <action_name name="i%3Alaunch%20phone"/>
    <action_name name="i%3Acall%20333"/>
    <action_name name="i%3Acall%20999"/>
    <action_name name="i%3Areturn%20to%20call%20in%20progress"/>
    <action_name name="i%3Aswap%20calls"/>
    <action_name name="i%3Areturn%20to%20homescreen"/>
    <action_name name="i%3Ahangup%20333"/>
    <action_name name="i%3Ahangup%20999"/>
    <tag_name name="homescreen"/>
    <tag_name name="phone"/>
    <test_engine>
        <tags enabled="homescreen"/>
        <remote msg="Assertion%20failure%20at%20adapter%28%29%20of%20tag%20%22homescreen%22%3A%20not%20in%20home%20screen%0ATraceback%20%28most%20recent%20call%20last%29%3A%0A%20%20File%20%22phone.aal%22%2C%20line%2081%2C%20in%20adapter%20of%20tag%20%22homescreen%22%0A%20%20%20%20assert%20d.waitBitmap%28%22home-dialer.png%22%29%2C%20%22not%20in%20home%20screen%22%0A"/>
Assertion failure at adapter() of tag "homescreen": not in home screen
Traceback (most recent call last):
  File "phone.aal", line 81, in adapter of tag "homescreen"
    assert d.waitBitmap("home-dialer.png"), "not in home screen"

```
    <status steps="0" coverage="0.000000" scov="0.000000e+00"/>
    <stop verdict="fail" reason="verifying%20tags%20%22homescreen%22%20failed."/>
    <current_time time="1456737060.391716"/>
    <elapsed_time time="6.794976"/>
</test_engine>
```

</conf_execute>
fail: verifying tags "homescreen" failed.
</fmbt_log>
✘-1 ~/git/fmbt-androidtest [master|✚ 1…171] 
10:11 $ 

using android 4.2.2 emulator based on Atom x86, fMBT on commit 46a6276ef1fd8b762c5f6b964bb1cff775000445, fmbt-androidtest on commit 4e060b000c9939dcd8ec5d22ffdd765d98438f89. The unlock element doesn't move enough to unlock the screen.

**Comment by askervin** [comment]
Great finding! fmbtandroid bug fixed in commit https://github.com/01org/fMBT/commit/44844f8d9eb36e618ca9035da335da2c8c08d0d6.

fmbtandroid moved to use Android's built-in swipe after 4.2, but once 4.2.X have been released, this should have been "starting from 4.3". Verified that swipe works on both 4.2.2 and 4.3.1, which are the only ones downloadable in SDK at the moment.

When installed and tried this test on a clean machine, I also noticed problems on verifying the homescreen even though the lock was successfully swiped. Therefore I relaxed bitmap comparison a bit in commit https://github.com/askervin/fmbt-androidtest/commit/6598da2623ddd8ee79763db082a9c658bd615c34. So please update both fmbt and fmbtandroid-test.

Thanks for reporting all the issues!

**Comment by shadeimi** [comment]
I'm a QA engineer, this is my work! :D i'm trying the patch right now :)

**Comment by shadeimi** [comment]
great, now it works!!! :D
